"""Regenerate MANIFEST.md with SHA256 of every image + label per split.

Required for patent enablement: proves that every published number comes
from a stable, hashed dataset. Also detects silent corruption.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


def _sha256(path: Path, chunk: int = 65536) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            b = f.read(chunk)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def _split_manifest(split_dir: Path) -> dict:
    entries = []
    img_dir = split_dir / "images"
    lbl_dir = split_dir / "labels"
    if not img_dir.exists():
        return {"split": split_dir.name, "count": 0, "entries": []}
    for img in sorted(img_dir.iterdir()):
        if img.suffix.lower() not in {".jpg", ".jpeg", ".png", ".bmp"}:
            continue
        lbl = lbl_dir / f"{img.stem}.txt"
        entries.append({
            "stem": img.stem,
            "image": img.name,
            "image_sha256": _sha256(img),
            "image_bytes": img.stat().st_size,
            "label": lbl.name if lbl.exists() else None,
            "label_sha256": _sha256(lbl) if lbl.exists() else None,
        })
    return {"split": split_dir.name, "count": len(entries), "entries": entries}


def _weights_manifest(weights_dir: Path) -> list[dict]:
    out = []
    if not weights_dir.exists():
        return out
    for p in sorted(weights_dir.iterdir()):
        if not p.is_file():
            continue
        out.append({
            "name": p.name,
            "sha256": _sha256(p),
            "bytes": p.stat().st_size,
        })
    return out


def _render_md(payload: dict, splits: list[str]) -> str:
    lines = [
        "# MANIFEST",
        "",
        "Auto-generated by `scripts/generate_manifest.py`. Do not hand-edit.",
        "",
        f"- Generated at: `{payload['generated_at']}`",
        f"- Dataset root: `{payload['dataset_root']}`",
        f"- Splits: `{', '.join(splits)}`",
        "",
        "## Summary",
        "",
        "| Split | Images | Total SHA256s |",
        "|---|---:|---:|",
    ]
    for s in payload["splits"]:
        lines.append(f"| {s['split']} | {s['count']} | {s['count']} |")

    lines += ["", "## Weights"]
    if payload["weights"]:
        lines += ["", "| File | SHA256 | Size |", "|---|---|---:|"]
        for w in payload["weights"]:
            lines.append(f"| `{w['name']}` | `{w['sha256']}` | {w['bytes']:,} |")
    else:
        lines.append("_(no weights directory found)_")

    lines += ["", "## Per-image hashes",
              "", "Full JSON: `MANIFEST.json`.  Preview (first 5 per split):", ""]
    for s in payload["splits"]:
        lines += [f"### {s['split']} (n={s['count']})", ""]
        lines += ["| stem | image sha256 | label sha256 |", "|---|---|---|"]
        for e in s["entries"][:5]:
            lbl = e["label_sha256"] or "—"
            lines.append(f"| `{e['stem']}` | `{e['image_sha256']}` | `{lbl}` |")
        if s["count"] > 5:
            lines.append(f"| … | … | … ({s['count'] - 5} more in JSON) |")
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate MANIFEST.md + MANIFEST.json")
    parser.add_argument("--data-dir", default="dataset_final_resplit")
    parser.add_argument("--weights-dir", default="production_models")
    parser.add_argument("--out-md", default="MANIFEST.md")
    parser.add_argument("--out-json", default="MANIFEST.json")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    splits = [d.name for d in data_dir.iterdir()
              if d.is_dir() and (d / "images").exists()]
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "dataset_root": str(data_dir),
        "splits": [_split_manifest(data_dir / s) for s in splits],
        "weights": _weights_manifest(Path(args.weights_dir)),
    }
    Path(args.out_json).write_text(json.dumps(payload, indent=2))
    Path(args.out_md).write_text(_render_md(payload, splits))
    print(f"wrote {args.out_md} and {args.out_json}")
    for s in payload["splits"]:
        print(f"  {s['split']:12} n={s['count']}")


if __name__ == "__main__":
    main()
